name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # or the name of your default branch, if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Build (if necessary)
      run: |
        npm install
        npm run build  # Assuming you have a build script in package.json that populates the ./dist directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

